cloudflareZoneId: 4a8d6a2fb498635183dd1433fe57d436
cloudflareRootDomain: parente.dev

# From https://dash.cloudflare.com/<account id>/parente.dev/ssl-tls/origin
cloudflareOriginCert: |
  -----BEGIN CERTIFICATE-----
  MIIEojCCA4qgAwIBAgIUW1oTtYm9pHOyw2pEtNshLK1DVnMwDQYJKoZIhvcNAQEL
  BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
  MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
  aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
  MB4XDTIwMTEyMjE5MjIwMFoXDTM1MTExOTE5MjIwMFowYjEZMBcGA1UEChMQQ2xv
  dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
  BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
  9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv6FyKY84H5ZbqxU3JcvzlkPvrB3J6Yz4m5X0
  gzbTvcFHKBBpAX+xAwx4vitiAvQcFrLO0DBYE5BViqei7aucZ1tn+X2Gwk5g0uKb
  JJ1WGNSAku8AaG9JTiiNHVShLwRMV6gI7ryrJtV6zNxHbpH4QjqCvg9+QWc08D2L
  0CFu0ohsR2pNFDW6Uo0Nq1Bx+KbGgm6Dkr08974BYHZA3Ig5BLKeDj8+IHYjj6ke
  IXJW04pdpVsy8mNXxTlWZ8yfq/0HffGJi9YJlO8tw4n1PAJ4mT+leJCZ8mSW4Dlk
  YQ8JmywtaH0diHkDaqfJLKJGqgsbWU7MYC9S0ezfpUwvWQsuoQIDAQABo4IBJDCC
  ASAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
  ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTiZR0Qwd1SszaF/rza0SC3RwEHiTAf
  BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
  MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
  YTAlBgNVHREEHjAcgg0qLnBhcmVudGUuZGV2ggtwYXJlbnRlLmRldjA4BgNVHR8E
  MTAvMC2gK6AphidodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9jYS5j
  cmwwDQYJKoZIhvcNAQELBQADggEBABlsuwjF96ZC6WnknEzIhDRJ3oUrA+7XAAd5
  06Mq0eu00iS/cmsNIOyPO3ds0SHwr7skqSS8KY5K2eR9V/wQTO2mE+3unMqtyv5Q
  4QW6AGOfw0j6B+ilqIB1f0mI1XQpbrg6y4VEwDCnY46BAFhSE6TzW5ub9sBdo7hH
  GrLEJ2/EOkPRkLJFuQggrVVS/FqZP4LsB5B03oo/VVqRWZ0JM7JSVxmX9R3Erup+
  2C8kA/K8uAAas4BY0/KGjmLTJzoBYZGqE9LVQN86MeHWfXv1bLwQ3apmLWUzKzs6
  5ej8uwGL2kL2mpS6dVH93zdoz6UQ6jpWHCsys7IywYND4lyXFWs=
  -----END CERTIFICATE-----

# From https://support.cloudflare.com/hc/en-us/articles/204899617-Authenticated-Origin-Pulls
cloudflareOriginPullCert: |
  -----BEGIN CERTIFICATE-----
  MIIGCjCCA/KgAwIBAgIIV5G6lVbCLmEwDQYJKoZIhvcNAQENBQAwgZAxCzAJBgNV
  BAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMRQwEgYDVQQLEwtPcmln
  aW4gUHVsbDEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzETMBEGA1UECBMKQ2FsaWZv
  cm5pYTEjMCEGA1UEAxMab3JpZ2luLXB1bGwuY2xvdWRmbGFyZS5uZXQwHhcNMTkx
  MDEwMTg0NTAwWhcNMjkxMTAxMTcwMDAwWjCBkDELMAkGA1UEBhMCVVMxGTAXBgNV
  BAoTEENsb3VkRmxhcmUsIEluYy4xFDASBgNVBAsTC09yaWdpbiBQdWxsMRYwFAYD
  VQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlhMSMwIQYDVQQD
  ExpvcmlnaW4tcHVsbC5jbG91ZGZsYXJlLm5ldDCCAiIwDQYJKoZIhvcNAQEBBQAD
  ggIPADCCAgoCggIBAN2y2zojYfl0bKfhp0AJBFeV+jQqbCw3sHmvEPwLmqDLqynI
  42tZXR5y914ZB9ZrwbL/K5O46exd/LujJnV2b3dzcx5rtiQzso0xzljqbnbQT20e
  ihx/WrF4OkZKydZzsdaJsWAPuplDH5P7J82q3re88jQdgE5hqjqFZ3clCG7lxoBw
  hLaazm3NJJlUfzdk97ouRvnFGAuXd5cQVx8jYOOeU60sWqmMe4QHdOvpqB91bJoY
  QSKVFjUgHeTpN8tNpKJfb9LIn3pun3bC9NKNHtRKMNX3Kl/sAPq7q/AlndvA2Kw3
  Dkum2mHQUGdzVHqcOgea9BGjLK2h7SuX93zTWL02u799dr6Xkrad/WShHchfjjRn
  aL35niJUDr02YJtPgxWObsrfOU63B8juLUphW/4BOjjJyAG5l9j1//aUGEi/sEe5
  lqVv0P78QrxoxR+MMXiJwQab5FB8TG/ac6mRHgF9CmkX90uaRh+OC07XjTdfSKGR
  PpM9hB2ZhLol/nf8qmoLdoD5HvODZuKu2+muKeVHXgw2/A6wM7OwrinxZiyBk5Hh
  CvaADH7PZpU6z/zv5NU5HSvXiKtCzFuDu4/Zfi34RfHXeCUfHAb4KfNRXJwMsxUa
  +4ZpSAX2G6RnGU5meuXpU5/V+DQJp/e69XyyY6RXDoMywaEFlIlXBqjRRA2pAgMB
  AAGjZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgECMB0GA1Ud
  DgQWBBRDWUsraYuA4REzalfNVzjann3F6zAfBgNVHSMEGDAWgBRDWUsraYuA4REz
  alfNVzjann3F6zANBgkqhkiG9w0BAQ0FAAOCAgEAkQ+T9nqcSlAuW/90DeYmQOW1
  QhqOor5psBEGvxbNGV2hdLJY8h6QUq48BCevcMChg/L1CkznBNI40i3/6heDn3IS
  zVEwXKf34pPFCACWVMZxbQjkNRTiH8iRur9EsaNQ5oXCPJkhwg2+IFyoPAAYURoX
  VcI9SCDUa45clmYHJ/XYwV1icGVI8/9b2JUqklnOTa5tugwIUi5sTfipNcJXHhgz
  6BKYDl0/UP0lLKbsUETXeTGDiDpxZYIgbcFrRDDkHC6BSvdWVEiH5b9mH2BON60z
  0O0j8EEKTwi9jnafVtZQXP/D8yoVowdFDjXcKkOPF/1gIh9qrFR6GdoPVgB3SkLc
  5ulBqZaCHm563jsvWb/kXJnlFxW+1bsO9BDD6DweBcGdNurgmH625wBXksSdD7y/
  fakk8DagjbjKShYlPEFOAqEcliwjF45eabL0t27MJV61O/jHzHL3dknXeE4BDa2j
  bA+JbyJeUMtU7KMsxvx82RmhqBEJJDBCJ3scVptvhDMRrtqDBW5JShxoAOcpFQGm
  iYWicn46nPDjgTU0bX1ZPpTpryXbvciVL5RkVBuyX2ntcOLDPlZWgxZCBp96x07F
  AnOzKgZk4RzZPNAxCXERVxajn/FLcOhglVAKo5H0ac+AitlQ0ip55D2/mf8o72tM
  fVQ6VpyjEXdiIXWUq/o=
  -----END CERTIFICATE-----

cloudflareOriginCertNamespaces:
  - default
