image:
  repository: ghcr.io/parente/cfsync
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env: []

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
