apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "self.fullname" .}}
  labels: {{- include "self.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{- include "self.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "self.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources: {{- toYaml .Values.resources | nindent 12}}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: PUSHOVER_APP_KEY
              value: {{.Values.env.PUSHOVER_APP_KEY}}
            - name: PUSHOVER_GROUP_KEY
              value: {{.Values.env.PUSHOVER_GROUP_KEY}}
            - name: STATE_FILE
              value: /data/etag
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{include "self.fullname" .}}
