schedule: "*/15 * * * *"

image:
  repository: minio/mc
  pullPolicy: IfNotPresent
  tag: ""

pvc:
  name: "data"
  localPath: "/data"

sourcePaths: []
destinationPath: "backup/"
minioUrl: ""
lifetime: "30d"

resources: {}
