replicaCount: 1

image:
  repository: ghcr.i/parente/justqr
  pullPolicy: IfNotPresent
  tag: latest

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts: []
  tls: []
