replicaCount: 1

image:
  repository: ghcr.io/parente/justqr
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts: []
  tls: []

affinity: {}
