releases:
  # Install the cfcidrwatch app to monitor for Cloudflare CIDR block changes and notify via Pushover
  - name: cfcidrwatch
    namespace: cfcidrwatch
    chart: homelab/cfcidrwatch
    version: 0.2.2
    atomic: true
    installed: true
    needs:
      - kube-system/retained-local-path
    values:
      - env:
          PUSHOVER_APP_KEY: {{.Values.pushoverAppKey}}
          PUSHOVER_GROUP_KEY: {{.Values.pushoverGroupKey}}
        resources:
          limits:
            cpu: 100m
            memory: 8Mi
          requests:
            cpu: 100m
            memory: 8Mi
  - name: cfcidrwatch-policy
    namespace: cfcidrwatch
    chart: ../charts/policy
    version: 0.1.0
    atomic: true
    installed: true
    values:
      - egress:
          enabled: true
          allowAllExcept: {{.Values.homeCIDR}}
