environments:
  default:
    values:
      - values.yaml
    secrets:
      - secrets.yaml
---
repositories:
  - name: homelab
    url: https://parente.github.io/homelab
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: stable
    url: https://charts.helm.sh/stable
helmfiles:
  - path: ./*.helmfile.yaml
    values:
      - {{toYaml .Values | nindent 8}}
