releases:
  # Install the honey.fitness origin certificate and key
  - name: cf-honey-fitness-origin-cert
    namespace: honey-fitness
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    installed: false
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: honey-fitness-tls
            type: kubernetes.io/tls
            data:
              tls.crt: {{.Values.honeyFitnessOriginCert | b64enc}}
              tls.key: {{.Values.honeyFitnessOriginKey | b64enc}}
  - name: honey-fitness
    namespace: honey-fitness
    chart: homelab/honey-fitness
    version: 0.2.0
    atomic: true
    installed: false
    needs:
      - honey-fitness/cf-honey-fitness-origin-cert
    values:
      - replicaCount: 2
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 16Mi
        ingress:
          hosts:
            - host: "honey.fitness"
              paths: ["/"]
            - host: "honey.{{.Values.defaultDomain}}"
              paths: ["/"]
          tls:
            - hosts: ["honey.fitness"]
              secretName: honey-fitness-tls
            - hosts: ["honey.{{.Values.defaultDomain}}"]
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - honey-fitness
                  topologyKey: kubernetes.io/hostname

  - name: honey-fitness-policy
    namespace: honey-fitness
    chart: homelab/policy
    version: 0.3.0
    atomic: true
    installed: {{.Values.installNetworkPolicies}}
    values:
      - egress:
          enabled: true
          allowAllExceptCIDR: {{.Values.homeCIDR}}
          allowAdditionalCIDR: {{- toYaml .Values.homelabHosts | nindent 12}}
        ingress:
          enabled: true
          allowNamespaces:
            - ingress-nginx
