releases:
  # Install the justqr web app to generate QR codes
  - name: justqr
    namespace: justqr
    chart: homelab/justqr
    version: 0.2.0
    atomic: true
    installed: false
    values:
      - replicaCount: 2
        resources:
          limits:
            cpu: 100m
            memory: 4Mi
          requests:
            cpu: 100m
            memory: 4Mi
        ingress:
          hosts:
            - host: "justqr.{{ .Values.defaultDomain }}"
              paths: ["/"]
          tls:
            - hosts: ["justqr.{{ .Values.defaultDomain }}"]
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - justqr
                  topologyKey: kubernetes.io/hostname
  - name: justqr-policy
    namespace: justqr
    chart: homelab/policy
    version: 0.3.0
    atomic: true
    installed: {{.Values.installNetworkPolicies}}
    values:
      - egress:
          enabled: false
        ingress:
          enabled: true
          allowNamespaces:
            - ingress-nginx
