releases:
  # Install the justqr web app to generate QR codes
  - name: justqr
    namespace: justqr
    chart: homelab/justqr
    version: 0.1.1
    atomic: true
    installed: true
    values:
      - replicaCount: 2
        resources:
          limits:
            cpu: 100m
            memory: 4Mi
          requests:
            cpu: 100m
            memory: 4Mi
        ingress:
          hosts:
            - host: "justqr.{{ .Values.defaultDomain }}"
              paths: ["/"]
          tls:
            - hosts: ["justqr.{{ .Values.defaultDomain }}"]
  - name: justqr-policy
    namespace: justqr
    chart: homelab/policy
    version: 0.1.0
    atomic: true
    installed: true
    values:
      - egress:
          enabled: false
