repositories:
  - name: minio
    url: https://operator.min.io/

releases:
  # Install minio-operator CRDs before the operator itself
  - name: minio-operator-crds
    namespace: minio-operator
    chart: kubernetes-incubator/raw
    version: 0.2.3
    atomic: true
    installed: false
    hooks:
      - events: ['presync']
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - https://raw.githubusercontent.com/minio/operator/v4.3.2/helm/minio-operator/crds/minio.min.io_tenants.yaml
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: helmfile-minio-operator-crds-installed
              namespace: minio-operator

  # Install minio operator and create a tenant
  # https://github.com/minio/operator/blob/master/helm/minio-operator
  - name: minio-operator
    namespace: minio-operator
    chart: minio/minio-operator
    version: 4.3.2
    needs:
      - minio-operator/minio-operator-crds
    atomic: true
    installed: false
    values:
      - tenants:
          - name: minio
            namespace: minio
            pools:
              - servers: 4
                volumesPerServer: 1
                size: 10Gi
                storageClassName: local-path
            secrets:
              enabled: true
              name: minio-secret
              accessKey: {{.Values.minioAccessKey}}
              secretKey: {{.Values.minioSecretKey}}
  # Install minio object storage service
  # https://github.com/minio/charts/tree/master/minio
  - name: minio
    namespace: minio
    chart: minio/minio
    version: 8.0.8
    atomic: true
    installed: false
    values:
      - accessKey: {{.Values.minioAccessKey}}
        secretKey: {{.Values.minioSecretKey}}
        mode: distributed
        replicas: 4
        environment:
          MINIO_BROWSER: on
        resources:
          requests:
            memory: 96Mi
          limits: 
            memory: 1024Gi
        persistence:
          size: 10Gi # per replica
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts: ["minio.{{ .Values.defaultDomain }}"]
  # Create ingresses for minio static site bucket prefixes
  - name: minio-static-sites
    namespace: minio
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    installed: false
    values:
      - resources:
          {{- range .Values.minioStaticSites}}
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: minio-{{.name}}-index
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/use-regex: "true"
                nginx.ingress.kubernetes.io/rewrite-target: {{.bucketPrefix}}/index.html
            spec:
              tls:
                - hosts: ["{{.host}}"]
              rules:
                - host: "{{.host}}"
                  http:
                    paths:
                      - path: /$
                        pathType: Prefix
                        backend:
                          service:
                            name: minio
                            port:
                              number: 9000
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: minio-{{.name}}
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/use-regex: "true"
                nginx.ingress.kubernetes.io/rewrite-target: {{.bucketPrefix}}/$1
            spec:
              tls:
                - hosts: ["{{.host}}"]
              rules:
                - host: "{{.host}}"
                  http:
                    paths:
                      - path: /(.+)$
                        pathType: Prefix
                        backend:
                          service:
                            name: minio
                            port:
                              number: 9000
          {{- end}}
  - name: minio-policy
    namespace: minio
    chart: homelab/policy
    version: 0.3.0
    atomic: true
    installed: {{.Values.installNetworkPolicies}}
    values:
      - egress:
          enabled: true
          allowAllExceptCIDR: {{.Values.homeCIDR}}
          allowAdditionalCIDR: {{- toYaml .Values.homelabHosts | nindent 12}}
        ingress:
          enabled: true
          # BUG: Webthings backup fails even if namespace listed. Timing? Allow all ingress for now.
          # allowNamespaces:
          #   - ingress-nginx
          #   - minio
          #   - webthings