repositories:
  - name: minio
    url: https://helm.min.io/

releases:
  # Install minio object storage service
  - name: minio
    namespace: minio
    chart: minio/minio
    version: 8.0.8
    atomic: true
    installed: true
    values:
      - accessKey: {{.Values.minioAccessKey}}
        secretKey: {{.Values.minioSecretKey}}
        mode: distributed
        replicas: 4
        environment:
          MINIO_BROWSER: on
        resources:
          requests:
            memory: 96Mi
          limits: 
            memory: 1024Gi
        persistence:
          size: 10Gi # per replica
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts: ["minio.{{ .Values.defaultDomain }}"]
  # Create ingresses for minio static site bucket prefixes
  - name: minio-static-sites
    namespace: minio
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    installed: true
    values:
      - resources:
          {{- range .Values.minioStaticSites}}
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: minio-{{.name}}-index
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/use-regex: "true"
                nginx.ingress.kubernetes.io/rewrite-target: {{.bucketPrefix}}/index.html
            spec:
              tls:
                - hosts: ["{{.host}}"]
              rules:
                - host: "{{.host}}"
                  http:
                    paths:
                      - path: /$
                        pathType: Prefix
                        backend:
                          service:
                            name: minio
                            port:
                              number: 9000
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: minio-{{.name}}
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/use-regex: "true"
                nginx.ingress.kubernetes.io/rewrite-target: {{.bucketPrefix}}/$1
            spec:
              tls:
                - hosts: ["{{.host}}"]
              rules:
                - host: "{{.host}}"
                  http:
                    paths:
                      - path: /(.+)$
                        pathType: Prefix
                        backend:
                          service:
                            name: minio
                            port:
                              number: 9000
          {{- end}}
  - name: minio-policy
    namespace: minio
    chart: homelab/policy
    version: 0.3.0
    atomic: true
    installed: true
    values:
      - egress:
          enabled: true
          allowAllExceptCIDR: {{.Values.homeCIDR}}
        ingress:
          enabled: true
          # BUG: Webthings backup fails even if namespace listed. Timing? Allow all ingress for now.
          # allowNamespaces:
          #   - ingress-nginx
          #   - minio
          #   - webthings