releases:
  - name: webthings
    namespace: webthings
    chart: homelab/webthings
    version: 1.0.0-r1
    atomic: true
    installed: true
    values:
      - nodeSelector:
          homelab/external-device: zwave-controller
        devices:
          - name: "zooz-zst10"
            path: "/dev/ttyACM0"
        ingress:
          hosts:
            - host: "things.{{ .Values.defaultDomain }}"
              paths: ["/"]
          tls:
            - hosts: ["things.{{ .Values.defaultDomain }}"]
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
  - name: webthings-backup
    namespace: webthings
    chart: homelab/minio-backup
    version: 0.1.1
    atomic: true
    installed: false
    values:
      - image:
          tag: RELEASE.2020-11-25T23-04-07Z
        sourcePaths:
          - "/data/config"
        destinationPath: backup/webthings/
        minioUrl: http://{{.Values.minioBackupAccessKey}}:{{.Values.minioBackupSecretKey}}@minio.minio.svc.cluster.local:9000
        schedule: "0 5 * * *"
        lifetime: "3d"
        pvc:
          name: webthings
          localPath: /data
        resources:
          requests:
            memory: 16Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 100m
  - name: webthings-policy
    namespace: webthings
    chart: homelab/policy
    version: 0.3.0
    atomic: true
    installed: {{.Values.installNetworkPolicies}}
    values:
      - egress:
          enabled: true
          allowAllExceptCIDR: {{.Values.homeCIDR}}
          allowAdditionalCIDR: {{- toYaml .Values.homelabHosts | nindent 12}}
        ingress:
          enabled: true
          allowNamespaces:
            - ingress-nginx
