releases:
  - name: webthings
    namespace: webthings
    chart: homelab/webthings
    version: 1.0.0-r1
    atomic: true
    installed: true
    values:
      - nodeSelector:
          homelab/external-device: zwave-controller
        devices:
          - name: "zooz-zst10"
            path: "/dev/ttyACM0"
        ingress:
          hosts:
            - host: "things.{{ .Values.defaultDomain }}"
              paths: ["/"]
          tls:
            - hosts: ["things.{{ .Values.defaultDomain }}"]
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
