releases:
  # (Optionally) Install the whoami app to test ingress
  - name: whoami
    namespace: default
    chart: homelab/whoami
    version: 0.1.0
    atomic: true
    installed: false
    values:
      - ingress:
          hosts:
            - host: "whoami.{{ .Values.defaultDomain }}"
              paths: ["/"]
          tls:
            - hosts: ["whoami.{{ .Values.defaultDomain }}"]
  - name: whoami-policy
    namespace: whoami
    chart: homelab/policy
    version: 0.1.0
    atomic: true
    installed: false
    values:
      - egress:
          enabled: true
          allowAllExcept: {{.Values.homeCIDR}}
