[package]
name = "justqr"
version = "0.1.0"
authors = ["Peter Parente <parente@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.4"
env_logger = "0.8"
qrcode = "0.12"
serde = "1.0"