apiVersion: v1
kind: Service
metadata:
  name: {{include "self.fullname" .}}
  labels: {{- include "self.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "self.selectorLabels" . | nindent 4}}
