apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "self.fullname" .}}
  labels: {{- include "self.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{- include "self.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "self.selectorLabels" . | nindent 8}}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{.Chart.Name}}
          securityContext:
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
          resources: {{- toYaml .Values.resources | nindent 12}}
