apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{include "self.fullname" .}}
  labels: {{- include "self.labels" . | nindent 4}}
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
  {{- if .Values.egress.enabled}}
  egress:
    - to:
        {{- if .Values.egress.allowAllExceptCIDR }}
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              {{- range .Values.egress.allowAllExceptCIDR}}
              - {{ . | quote }}
              {{- end }}
        {{- end }}
        {{- range .Values.egress.allowAdditionalCIDR }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
  {{- end}}
  {{- if .Values.ingress.enabled }}
  ingress:
    {{- if .Values.ingress.allowNamespaces }}
    - from:
        {{- range .Values.ingress.allowNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . | quote }}
        {{- end }}
    {{- else }}
    - {}
    {{- end }}
  {{- end}}