apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{include "self.fullname" .}}
  labels: {{- include "self.labels" . | nindent 4}}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.egress.enabled}}
    - to:  
        {{- if .Values.egress.allowAllExcept }}
        - ipBlock:
            cidr: 0.0.0.0/0
            {{- with .Values.egress.allowAllExcept}}
            except: {{- toYaml . | nindent 14}}
            {{- end }}
        {{- end }}
        {{- range .Values.egress.allowAdditionalCIDR }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
    {{- else }}
      - {}
    {{- end}}