replicaCount: 1

image:
  repository: ghcr.io/parente/honey-fitness
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts: []
  tls: []
