name: Release webapp

on:
  push:
    tags:
      - "webapp-*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release helm charts to GitHub Pages
        uses: stefanprodan/helm-gh-pages@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
