name: Release cfcidrwatch

on:
  push:
    tags:
      - "cfcidrwatch-*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag as version number
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/cfcidrwatch-}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push cfcidrwatch docker image
        uses: docker/build-push-action@v2
        with:
          context: ./cfcidrwatch
          file: ./cfcidrwatch/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: |
            ghcr.io/parente/cfcidrwatch:${{ steps.get_version.outputs.version }}
            ghcr.io/parente/cfcidrwatch:latest

      - name: Release helm charts to GitHub Pages
        uses: stefanprodan/helm-gh-pages@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
